spring.application.name=infosales
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dipanshu123450@gmail.com
spring.mail.password=erqp igig smtj djjr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true